@startuml

actor Client
participant CombatController
participant CombatDao
participant PersonnageDao
participant CombatService
participant Model
participant ThymeleafView

Client -> CombatController: attaquer(idCombat, idCible, model)
activate CombatController

CombatController -> CombatDao: combatDao.findById(idCombat)
activate CombatDao

CombatController -> PersonnageDao: personnageDao.findById(idCible)
activate PersonnageDao

CombatController -> CombatService: verificationFinCombat()
activate CombatService

note over CombatService: Vérification de la fin du combat

alt Combat n'est pas terminé
    CombatService -> CombatDao: combatDao.findById(idCombat)
    activate CombatDao

    CombatService -> CombatService: combattre()
    activate CombatService

    CombatService -> CombatDao: combatDao.findById(idCombat)
    activate CombatDao

    CombatService -> Model: model.addAttribute("messages", lesMessages)
    activate Model

    CombatService -> Model: model.addAttribute("combat", combatApresTour)
    activate Model

    CombatController -> ThymeleafView: "joueur/combat/index"
    activate ThymeleafView

else Combat est terminé
    CombatController -> ThymeleafView: "redirect:/joueur/campagne/{id}/play"
    activate ThymeleafView
end

deactivate CombatController
deactivate CombatDao
deactivate PersonnageDao
deactivate CombatService
deactivate Model
deactivate ThymeleafView

@enduml
